name: .NET Standard

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Standard
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108   
    - name: CD to working directory
      run: cd MoonPhaseSettings
    - name: Build with dotnet
      run: msbuild MoonPhaseSettings\MoonPhaseSettings.sln -p:Configuration=Release
